grep('2005-Intensive Care (Special Edition)/01-GhostsGTChords.txt','2005output/Ghosts.txt')
grep('2005-Intensive Care (Special Edition)/02-TrippingGTChords.txt','2005output/Tripping.txt')
grep('2005-Intensive Care (Special Edition)/03-Make Me PureGTChords.txt','2005output/MakeMePure.txt')
grep('2005-Intensive Care (Special Edition)/04-Spread Your WingsGTChords.txt','2005output/SpreadYourWings.txt')
grep('2005-Intensive Care (Special Edition)/05-Advertising SpaceGTChords.txt','2005output/AdvertisingSpace.txt')
grep('2005-Intensive Care (Special Edition)/06-Please Don''t DieGTChords.txt','2005output/PleaseDontDie.txt')
grep('2005-Intensive Care (Special Edition)/07-Your Gay FriendGTChords.txt','2005output/YourGayFriend.txt')
grep('2005-Intensive Care (Special Edition)/08-Sin Sin SinGTChords.txt','2005output/SinSinSin.txt')
grep('2005-Intensive Care (Special Edition)/09-Random Acts Of KindnessGTChords.txt','2005output/RandomActsKindness.txt')
grep('2005-Intensive Care (Special Edition)/10-The Trouble With MeGTChords.txt','2005output/TheTroubleWithMe.txt')