grep('2000-Sing When You ''re Winning/01-Let Love Be Your EnergyGTChords.txt','2000output/LetLoveBeYourEnergy.txt')
grep('2000-Sing When You ''re Winning/02-Better ManGTChords.txt','2000output/BetterMan.txt')
grep('2000-Sing When You ''re Winning/03-Rock DJGTChords.txt','2000output/RockDJ.txt')
grep('2000-Sing When You ''re Winning/04-SupremeGTChords.txt','2000output/Supreme.txt')
grep('2000-Sing When You ''re Winning/05-KidsGTChords.txt','2000output/Kids.txt')
grep('2000-Sing When You ''re Winning/06-If It''s Hurting YouGTChords.txt','2000output/IfHurtingYou.txt')
grep('2000-Sing When You ''re Winning/07-Singing For The LonelyGTChords.txt','2000output/SingingForTheLonely.txt')
grep('2000-Sing When You ''re Winning/08-Love Calling EarthGTChords.txt','2000output/LoveCallingEarth.txt')
grep('2000-Sing When You ''re Winning/09-Knutsford City LimitsGTChords.txt','2000output/KnutsfordCity.txt')
grep('2000-Sing When You ''re Winning/10-Forever TexasGTChords.txt','2000output/ForeverTexas.txt')